export const CoursesData = [
  {
    id: 101,
    name: 'JavaScript for beginners',
    author: 'Anukul',
    duration: 48,
    type: 'Free',
    price: 0.0,
    rating: 4.1,
    image: '/assets/js.png',
    description:
      "JavaScript is a high-level, interpreted programming language that is primarily used for adding interactivity and dynamic behavior to web pages. It is one of the core technologies used for building websites and web applications. JavaScript can be executed on the client-side (in the user's web browser) as well as on the server-side (using technologies like Node.js).",
  },
  {
    id: 102,
    name: 'Angular for beginners',
    author: 'John',
    duration: 30,
    type: 'Premium',
    price: 499,
    rating: 4.4,
    image: '/assets/ng.png',
    description:
      'Angular is a popular and powerful front-end development framework for building web applications. It is a TypeScript-based framework developed and maintained by Google. Angular allows developers to build dynamic and robust applications by providing a structured and modular approach to web development.',
  },
  {
    id: 103,
    name: 'React for beginners',
    author: 'Carry',
    duration: 43,
    type: 'Free',
    price: 0.0,
    rating: 4.8,
    image: './assets/react.png',
    description:
      'React is a popular JavaScript library for building user interfaces. It was developed by Facebook and is widely used for creating interactive and dynamic web applications. React follows a component-based approach, allowing developers to build reusable UI components that update efficiently and declaratively in response to changes in application state.',
  },
  {
    id: 104,
    name: 'Advance Angular Course',
    author: 'Anukul',
    duration: 48,
    type: 'Premium',
    price: 499.0,
    rating: 4.8,
    image: '/assets/ang.jpeg',
    description:
      'Advanced Angular refers to the deeper and more complex concepts, techniques, and features of the Angular framework. It builds upon the foundational knowledge of Angular and delves into more advanced topics to enhance your ability to build sophisticated and scalable web applications.',
  },
  {
    id: 105,
    name: 'Advance JavaScript Course',
    author: 'Anukul',
    duration: 60,
    type: 'Free',
    price: 499.0,
    rating: 4.9,
    image: '/assets/aJs.jpeg',
    description:
      'Advanced JavaScript refers to the deeper and more complex concepts, techniques, and features of the JavaScript programming language. It builds upon the foundational knowledge of JavaScript and delves into more advanced topics to enhance the capabilities and efficiency of your code. Here are some key areas of advanced JavaScript:',
  },
  {
    id: 106,
    name: 'Advance React Course',
    author: 'Mosh',
    duration: 32,
    type: 'Premium',
    price: 499.0,
    rating: 4.8,
    image: '/assets/aReact.png',
    description:
      'Advanced React refers to the deeper and more complex concepts, techniques, and features of the React library. It goes beyond the basics and explores advanced topics to help you build more efficient, scalable, and sophisticated React applications.',
  },
  {
    id: 107,
    name: 'Python for beginners',
    author: 'Anukul',
    duration: 44,
    type: 'Free',
    price: 0.0,
    rating: 4.4,
    image: '/assets/python.png',
    description:
      'Python is a high-level, versatile, and interpreted programming language known for its simplicity and readability. It was created by Guido van Rossum and first released in 1991. Python has gained immense popularity among developers due to its ease of use, extensive libraries, and broad range of applications.',
  },
  {
    id: 108,
    name: 'C++ for beginners',
    author: 'Anukul',
    duration: 45,
    type: 'Free',
    price: 0.0,
    rating: 4.1,
    image: '/assets/c++.webp',
    description:
      'C++ is a powerful and widely used general-purpose programming language. It was developed as an extension of the C programming language and provides additional features for object-oriented programming (OOP). C++ is known for its efficiency, flexibility, and ability to produce high-performance code.',
  },
  {
    id: 109,
    name: 'Java for beginners',
    author: 'Anukul',
    duration: 38,
    type: 'Premium',
    price: 599.0,
    rating: 4.1,
    image: '/assets/Java-Logo.jpeg',
    description:
      'Java is a popular and widely used programming language known for its simplicity, platform independence, and versatility. It was developed by James Gosling and first released in 1995. Java is designed to be portable, secure, and robust, making it suitable for a wide range of applications, from desktop software to web development and mobile app development.',
  },
  {
    id: 110,
    name: 'HTML/CSS for beginners',
    author: 'Anukul',
    duration: 38,
    type: 'Free',
    price: 0.0,
    rating: 4.1,
    image: '/assets/html.jpeg',
    description:
      'HTML (Hypertext Markup Language) and CSS (Cascading Style Sheets) are fundamental technologies used for creating and styling web pages. They work together to structure and present the content of a web page. HTML is responsible for defining the structure and content of a web page. It consists of a series of tags that enclose different elements such as headings, paragraphs, images, links, tables, forms, and more. HTML provides the basic framework for organizing and displaying information on the web.CSS, on the other hand, is used to style and visually enhance the HTML elements. It allows you to control the layout, colors, fonts, sizes, and other visual aspects of the web page. CSS works by applying styles to HTML elements using selectors and property-value pairs.',
  },
];
